crewAIInc/crewAI-tools

- crewai_tools/tools/base_tool.py
- tests/base_tool_test.py
Allow us to control cache per tool on the main library
> adding cache_function to base_tool

- crewai_tools/tools/code_docs_search_tool/code_docs_search_tool.py
- crewai_tools/tools/csv_search_tool/csv_search_tool.py
- crewai_tools/tools/directory_search_tool/directory_search_tool.py
- crewai_tools/tools/docx_search_tool/docx_search_tool.py
- crewai_tools/tools/github_search_tool/github_search_tool.py
- crewai_tools/tools/json_search_tool/json_search_tool.py
- crewai_tools/tools/mdx_seach_tool/mdx_search_tool.py
- crewai_tools/tools/pg_seach_tool/pg_search_tool.py
- crewai_tools/tools/txt_search_tool/txt_search_tool.py
- crewai_tools/tools/website_search/website_search_tool.py
- crewai_tools/tools/xml_search_tool/xml_search_tool.py
- crewai_tools/tools/youtube_channel_search_tool/youtube_channel_search_tool.py
- crewai_tools/tools/youtube_video_search_tool/youtube_video_search_tool.py
Not loving it, but we need this change to move faster to the release.
> Fix RAG tools

- crewai_tools/tools/code_docs_search_tool/code_docs_search_tool.py
- crewai_tools/tools/csv_search_tool/csv_search_tool.py
- crewai_tools/tools/directory_search_tool/directory_search_tool.py
- crewai_tools/tools/docx_search_tool/docx_search_tool.py
- crewai_tools/tools/github_search_tool/README.md
- crewai_tools/tools/github_search_tool/github_search_tool.py
- crewai_tools/tools/json_search_tool/json_search_tool.py
- crewai_tools/tools/mdx_seach_tool/mdx_search_tool.py
- crewai_tools/tools/pdf_search_tool/pdf_search_tool.py
- crewai_tools/tools/txt_search_tool/txt_search_tool.py
- crewai_tools/tools/website_search/website_search_tool.py
- crewai_tools/tools/xml_search_tool/xml_search_tool.py
- crewai_tools/tools/youtube_channel_search_tool/youtube_channel_search_tool.py
- crewai_tools/tools/youtube_video_search_tool/youtube_video_search_tool.py
While we don't get along with pydantic, let's do this.
> Fix tool descriptions

- crewai_tools/tools/serper_dev_tool/serper_dev_tool.py
Pretty much what it says on the tin. :)
> Fix wrong comments / descriptions for SerperDevTool

- crewai_tools/__init__.py
- crewai_tools/tools/__init__.py
- crewai_tools/tools/browserbase_load_tool/README.md
- crewai_tools/tools/browserbase_load_tool/browserbase_load_tool.py
This PR adds BrowserbaseLoadTool to enable loading URLs via a headless web browser and returning the results
> added BrowserbaseLoadTool

- crewai_tools/tools/browserbase_load_tool/browserbase_load_tool.py
Hey,
just occurred to me that my last contribution had a bug.
Have tested this fix on my machine.
> Updated Browserbase load tool

- crewai_tools/tools/file_read_tool/file_read_tool.py
This pull request introduces an enhancement to the `FileReadTool` within our `crewai_tools` package, focusing on improving the robustness and user experience when reading files. Previously, an unhandled exception during the file reading operation could halt the entire process, potentially disrupting workflows. The proposed changes aim to address this by implementing error handling mechanisms that ensure continuity in operations, even in the face of errors.
- **Code Formatting**: Adjusted indentation and spacing to improve readability and maintain consistency with our Python style guide.
- **Error Handling**: Wrapped the file reading operation within a `try-except` block. This change catches any exceptions that may occur during the file reading process, preventing the entire tool from …
> Improve File Reading Robustness in FileReadTool

- crewai_tools/tools/serper_dev_tool/serper_dev_tool.py
In original code n_results is always None so you always get only 10 results from Serper. With this change, when you explicitly set the n_results parameter when creating a SerperDevTool object it is taken into account.
> Update serper_dev_tool.py consider n_results parameter

- crewai_tools/__init__.py
Add import from Code Interpreter tool to Tools
> fix: add code interpreter tool

- crewai_tools/tools/code_interpreter_tool/code_interpreter_tool.py
Fix type hinting, add container name and handle exception and returned old description
> fix: fix type hinting, add container name and handle exception and returned old description

- crewai_tools/tools/scrape_website_tool/scrape_website_tool.py
fixed problem with garbage output of ScrapeWebsiteTool on some websites
> bugfix: ScrapeWebsiteTool encoding

- crewai_tools/tools/serper_dev_tool/serper_dev_tool.py
fixed the usage of n_results argument and 'continue' on KeyError instead of 'next'
> fixed use of arg n_results

- crewai_tools/tools/browserbase_load_tool/README.md
- crewai_tools/tools/browserbase_load_tool/browserbase_load_tool.py
added sessions support, proxies
> updated browserbase tool

- crewai_tools/tools/github_search_tool/README.md
The LLM generated name for RAG was wrong.
> Corrected the acronym 'RAG'

- crewai_tools/tools/code_interpreter_tool/README.md
- crewai_tools/tools/code_interpreter_tool/code_interpreter_tool.py
This PR intends to add the ability of the Container to have the local folder as available volume and add the possibility for the user to use their own Dockerfile
> feat: Add volume option

- README.md
- pyproject.toml
This PR Updates the existing GH links to new repo and also updates readme.md
> Updated GitHub repo links and readme.md

- crewai_tools/__init__.py
ref: https://github.com/crewAIInc/crewAI-tools/pull/83
fix: SpiderTool import
> fix: SpiderTool import

- crewai_tools/__init__.py
- crewai_tools/tools/__init__.py
- crewai_tools/tools/brave_search_tool/README.md
- crewai_tools/tools/brave_search_tool/brave_search_tool.py
- tests/tools/brave_search_tool_test.py
add tool for Brave Web Search API to query Brave Search and get back search results from the web
> add brave search tool

- crewai_tools/tools/firecrawl_crawl_website_tool/firecrawl_crawl_website_tool.py
Related to Issue #131 
Similar solution to PR https://github.com/crewAIInc/crewAI-tools/pull/132
> Fix pydantic related errors on FirecrawlCrawlWebsiteTool

- crewai_tools/tools/jina_scrape_website_tool/README.md
- crewai_tools/tools/jina_scrape_website_tool/jina_scrape_website_tool.py
I created a website scraper that uses Jina.ai reader service: https://jina.ai/reader/
Thanks for the idea to one of our customers! Corey!
> Jina Website Scraper v1

- crewai_tools/tools/spider_tool/README.md
- crewai_tools/tools/spider_tool/spider_tool.py
As part of Spider team, I noticed that the SpiderTool isn't working properly for some users—so this PR addresses the issue and added a few enhancements.
This PR fixes the issues so the tool works much more reliably (especially when using a faster model like gpt-4o-mini) by simplifying the tool input fields. Additionally, the tool now allows for custom parameters to be passed to further customize the API based on specific use cases such as needing the return format of the content to be in HTML instead. 
This addresses similar SpiderTool issues posted in the [CrewAI forums here](https://community.crewai.com/t/spider-web-scraper/1612/9). 
- Input schema for SpiderTool is now simpler and more reliable. Before the LLM easily messes up the input fields.
- Better error handling
- URL validation …
> Fix(SpiderTool): Improve Tool Reliability and Performance

- crewai_tools/tools/firecrawl_crawl_website_tool/firecrawl_crawl_website_tool.py
- crewai_tools/tools/firecrawl_scrape_website_tool/firecrawl_scrape_website_tool.py
- crewai_tools/tools/firecrawl_search_tool/firecrawl_search_tool.py
I accidentally broke our firecrawl tools with a fix I just introduced earlier today.
Now, everything is running properly again!
> Fix firecrawl errors

- crewai_tools/__init__.py
- crewai_tools/tools/__init__.py
- crewai_tools/tools/hyperbrowser_load_tool/README.md
- crewai_tools/tools/hyperbrowser_load_tool/hyperbrowser_load_tool.py
- pyproject.toml
- uv.lock
This PR introduces the [Hyperbrowser](https://hyperbrowser.ai) tool integration that allows CrewAI users to load the contents from a website by either scraping or crawling it.
> added HyperbrowserLoadTool

- crewai_tools/tools/ocr_tool/README.md
- crewai_tools/tools/ocr_tool/ocr_tool.py
> OCR Tool v1

- crewai_tools/tools/databricks_query_tool/databricks_query_tool.py
Databricks is an optional dependency, but the tool package is imported by default, leading to `ImportError` exceptions.
Related https://github.com/crewaIInc/crewai/issues/2390
> Conditionally import Databricks library

- crewai_tools/tools/patronus_eval_tool/patronus_local_evaluator_tool.py
- crewai_tools/tools/rag/rag_tool.py
- crewai_tools/tools/scrapegraph_scrape_tool/scrapegraph_scrape_tool.py
- crewai_tools/tools/selenium_scraping_tool/selenium_scraping_tool.py
- crewai_tools/tools/vision_tool/vision_tool.py
A several warnings were addressed following by  https://docs.pydantic.dev/2.10/migration
> feat: cleanup Pydantic warning

- crewai_tools/tools/qdrant_vector_search_tool/README.md
- crewai_tools/tools/qdrant_vector_search_tool/qdrant_search_tool.py
**Description:**
This PR improves the QdrantVectorSearchTool by adding support for scenarios where the Qdrant API key is not provided and need to fallback to local client.
**Issue Reference:**
Closes #249
> #249 feat: add support for local qdrant client

- crewai_tools/tools/selenium_scraping_tool/selenium_scraping_tool.py
- tests/tools/selenium_scraping_tool_test.py
Closes https://github.com/crewAIInc/crewAI/issues/2127
- Refactor Selenium scraping tool to use single driver instance 
- Add headless mode configuration for Chrome 
- Improve error handling with try/finally 
- Simplify code structure and improve maintainability
> refactor(selenium): improve driver management and add headless mode

- crewai_tools/tools/file_read_tool/README.md
- crewai_tools/tools/file_read_tool/file_read_tool.py
- tests/file_read_tool_test.py
This PR enhances the FileReadTool by adding the ability to read specific portions of files rather than loading entire files into memory. Users can now specify a starting line and number of lines to read, which is particularly useful when working with large files.
- Added `start_line` parameter (1-indexed) to specify where to begin reading
- Added `line_count` parameter to control how many lines to read
- Maintains backward compatibility with existing functionality
- Provides proper error handling for out-of-range requests
- Updated `FileReadToolSchema` with two new optional parameters:
- `start_line`: Default is 1 (first line)
- `line_count`: Default is None (read to end of file)
- Enhanced `_run()` method to handle partial file reading
- Added appropriate validation and error messages
- …
> Add chunk reading functionality to FileReadTool

- pyproject.toml
This patch release includes:
Allow setting custom LLM for the vision tool (#294)
Fix firecrawl tool to resolve positional arguments issue (#275)
> Update version to 0.42.3 in pyproject.toml

- generate_tool_specs.py
- tests/test_generate_tool_specs.py
- tool.specs.json
We’re currently using the JSON Schema standard for these fields
> refactor: renaming init_params and run_params to reflect their schema. #332

- .github/workflows/tests.yml
Add SQLite FTS5 module to GitHub Actions test workflow
- Tests should run with FTS5 support
> Add SQLite FTS5 support to test workflow

- .github/workflows/tests.yml
For more details check out [here](https://github.com/actions/runner-images/issues/12576)
> test: remove workaround related to SQLite without FTS5

- crewai_tools/aws/__init__.py
- crewai_tools/aws/bedrock/__init__.py
- crewai_tools/aws/bedrock/browser/README.md
- crewai_tools/aws/bedrock/browser/__init__.py
- crewai_tools/aws/bedrock/browser/browser_session_manager.py
- crewai_tools/aws/bedrock/browser/browser_toolkit.py
- crewai_tools/aws/bedrock/browser/utils.py
- crewai_tools/aws/bedrock/code_interpreter/README.md
- crewai_tools/aws/bedrock/code_interpreter/__init__.py
- crewai_tools/aws/bedrock/code_interpreter/code_interpreter_toolkit.py
- pyproject.toml
- uv.lock
This PR adds two new toolkits that integrate AWS Bedrock's Browser and Code Interpreter capabilities with CrewAI:
1. Browser Tools: Enable agents to navigate websites, extract content, and interact with web pages
2. Code Interpreter Tools: Allow agents to execute code, run commands, and manage files in an isolated environment
```bash
pip install crewai-tools
pip install bedrock-agentcore playwright beautifulsoup
```
```python
from crewai import Agent, Task, Crew
from crewai_tools.aws import create_browser_toolkit
toolkit, browser_tools = create_browser_toolkit(region="us-west-2")
researcher = Agent(
role="Web Researcher",
goal="Research online content",
tools=browser_tools
)
task = Task(
description="Navigate to example.com and extract text",
agent=researcher
)
crew = …
```
> Bedrock AgentCore browser and code interpreter toolkits

- crewai_tools/__init__.py
- crewai_tools/tools/__init__.py
- crewai_tools/tools/serper_scrape_website_tool/serper_scrape_website_tool.py
I will follow up with documentation.
> feat: add SerperScrapeWebsiteTool for extracting clean content from URLs

- crewai_tools/__init__.py
- crewai_tools/tools/__init__.py
Fixes [#3210](https://github.com/crewAIInc/crewAI/issues/3210)
> chore: make tavily tools exportable

- crewai_tools/adapters/mcp_adapter.py
- tests/adapters/mcp_adapter_test.py
Fixes: https://github.com/crewAIInc/crewAI/issues/3254
> feat: allow custom client_timeout for MCPAdapter

- pyproject.toml
- uv.lock
- Copied ruff configuration from main crewAI repository for consistent linting
- Aligned dev dependency versions with crewAI project
- Removed unnecessary tool.hatch.metadata and tool.uv sections
> chore: sync ruff configuration and dev dependencies with crewAI
