.gitignore
crewai_tools/adapters/embedchain_adapter.py
crewai_tools/adapters/lancedb_adapter.py
crewai_tools/tools/base_tool.py
crewai_tools/tools/code_docs_search_tool/code_docs_search_tool.py
crewai_tools/tools/csv_search_tool/csv_search_tool.py
crewai_tools/tools/directory_search_tool/directory_search_tool.py
crewai_tools/tools/docx_search_tool/docx_search_tool.py
crewai_tools/tools/github_search_tool/github_search_tool.py
crewai_tools/tools/json_search_tool/json_search_tool.py
crewai_tools/tools/mdx_seach_tool/mdx_search_tool.py
crewai_tools/tools/pdf_search_tool/pdf_search_tool.py
crewai_tools/tools/pg_seach_tool/pg_search_tool.py
crewai_tools/tools/rag/README.md
crewai_tools/tools/rag/rag_tool.py
crewai_tools/tools/txt_search_tool/txt_search_tool.py
crewai_tools/tools/website_search/website_search_tool.py
crewai_tools/tools/xml_search_tool/xml_search_tool.py
crewai_tools/tools/youtube_channel_search_tool/youtube_channel_search_tool.py
crewai_tools/tools/youtube_video_search_tool/youtube_video_search_tool.py
tests/tools/rag/rag_tool_test.py

Yeah, the plan was to simply allow people to configure the model to use in RAG tools instead of going with the default OpenAI, but I ended up refactoring some stuff.
The thing is now you can create any tool with a config dictionary, as it follows:
```python
tool = TXTSearchTool(
config=dict(
llm=dict(
provider="openai",
config=dict(model="gpt-3.5-custom"),
),
embedder=dict(
provider="google",
config=dict(model="models/embedding-001"),
),
)
)
```
In the process of writing this, a few decisions were made. To point a few:
* RAG tool adapters now also have to implement an `add` method to insert the given data into their inner stores.
* The generic RAG tool also includes an `add` method that simply forwards the content to the adapter. Subclasses override such method to simplify the process for …

Custom model config for RAG tools

---

crewai_tools/tools/docx_search_tool/docx_search_tool.py

This pull request addresses a `TypeError` encountered in the `FixedDOCXSearchToolSchema` due to incorrect usage of `Optional` with `Field`. The error was triggered during the import process, causing instantiation issues with `typing.Union`.
- Corrected the usage of `Optional` in the `docx_search_tool.py` to properly define optional fields with Pydantic's `Field`.
- **File Affected**: `docx_search_tool.py`
- **Error Trace**:
```
TypeError: Cannot instantiate typing.Union
```
This error occurred due to an attempt to instantiate `Optional` as a class, which is not permissible. `Optional` should be used as a type hint, not as a callable.
Updated the field definition to:
```python
docx: Optional[str] = Field(..., description="Mandatory docx path you want to search")
```
This update ensures …

Fix TypeError in DOCXSearchTool Schema

---

crewai_tools/__init__.py
crewai_tools/tools/__init__.py
crewai_tools/tools/llamaindex_tool/README.md
crewai_tools/tools/llamaindex_tool/llamaindex_tool.py

allow two modes of including llamaindex as a module for crewAI agents: 
- plug in a llamaindex tool as a crewAI tool (e.g. a function tool or a tool from llamahub) 
- plug in a llamaindex query engine, autoconvert to a crewAI tool (e.g. from a RAG pipeline) 
notebook incoming!

add llamaindex tool 

---

crewai_tools/tools/firecrawl_crawl_website_tool/README.md
crewai_tools/tools/firecrawl_crawl_website_tool/firecrawl_crawl_website_tool.py
crewai_tools/tools/firecrawl_scrape_website_tool/README.md
crewai_tools/tools/firecrawl_scrape_website_tool/firecrawl_scrape_website_tool.py
crewai_tools/tools/firecrawl_search_tool/README.md
crewai_tools/tools/firecrawl_search_tool/firecrawl_search_tool.py

This PR introduces [Firecrawl](https://www.firecrawl.dev/) tools, enabling the following features:
- Scrape (with LLM Extraction)
- Crawl
- Search
@joaomdmoura, hope you don't mind me just doing a PR, haha! Thank you for creating this amazing tool!

added Firecrawl tools

---

crewai_tools/tools/base_tool.py

The agent doesn't recieve descriptions of the tools arguments. This PR added the args description to tool description so agent will know how to use them.

arguments descriptions added to tool description

---

crewai_tools/tools/selenium_scraping_tool/selenium_scraping_tool.py

This PR fixes the import of Firefox options, replacing it with Chrome options.
The default WebDriver defined is Chrome:
https://github.com/joaomdmoura/crewAI-tools/blob/5dc3bdb1ccee98467a0355840a8dcfe1cf4088c0/crewai_tools/tools/selenium_scraping_tool/selenium_scraping_tool.py#L26
However, the imported options is for Firefox, resulting in a failure to use the Selenium scraping tool.
```
from crewai_tools import SeleniumScrapingTool
tool = SeleniumScrapingTool()
tool = SeleniumScrapingTool(website_url='https://www.selenium.dev/selenium/web/web-form.html')
text = tool.run()
print(text)
```
```
python tests/web_scraper.py 
Using Tool: Read a website content
...
File "/home/marcelo/crewai/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response …
```

Fix: Selenium incorrect firefox options import

---

crewai_tools/adapters/pdf_embedchain_adapter.py
crewai_tools/tools/pdf_search_tool/pdf_search_tool.py

See: https://github.com/joaomdmoura/crewAI-tools/issues/63
Currently, when a PDF file-path is passed into the PDFSearchTool, the results returned from the PDFSearchTool are not limited to the passed-in PDF, and will return the top relevant information matching the search tool's query, from the vector database, regardless of which PDF was passed into the tool.
This pull request fixes that.
The scope of the impact of this change is limited by creating a PDF embedchain adapter which is specific to the PDF search tool, and which is nearly identical to embedchain adapter, with only a few changes. Namely:
- a pdf "src" is added to the adapter when the pdf is added to the vector database in the add() method
- a where clause is created to filter the results queried from the vector database to …

Limit PDF search results to the provided PDF (IF a PDF is provided)

---

crewai_tools/tools/code_docs_search_tool/code_docs_search_tool.py
crewai_tools/tools/csv_search_tool/csv_search_tool.py
crewai_tools/tools/directory_search_tool/directory_search_tool.py
crewai_tools/tools/docx_search_tool/docx_search_tool.py
crewai_tools/tools/github_search_tool/github_search_tool.py
crewai_tools/tools/json_search_tool/json_search_tool.py
crewai_tools/tools/mdx_seach_tool/mdx_search_tool.py
crewai_tools/tools/pg_seach_tool/pg_search_tool.py
crewai_tools/tools/txt_search_tool/txt_search_tool.py
crewai_tools/tools/website_search/website_search_tool.py
crewai_tools/tools/xml_search_tool/xml_search_tool.py
crewai_tools/tools/youtube_channel_search_tool/youtube_channel_search_tool.py
crewai_tools/tools/youtube_video_search_tool/youtube_video_search_tool.py

- Fixed an issue where multiple RagTool based tools failed to function if parameters were provided after tool creation.
- Updated tools to correctly process source file/URL passed by the agent post-creation as per documentation.
Closes[ #<47>](https://github.com/joaomdmoura/crewAI-tools/issues/47)

fix: Ensure tools handle parameters passed post-creation correctly

---

crewai_tools/tools/firecrawl_crawl_website_tool/firecrawl_crawl_website_tool.py
crewai_tools/tools/firecrawl_scrape_website_tool/firecrawl_scrape_website_tool.py
crewai_tools/tools/firecrawl_search_tool/firecrawl_search_tool.py

Customers were encountering the following error from the agent:
```
I encountered an error while trying to use the tool. This was the error: argument of type 'NoneType' is not iterable.
Tool Firecrawl web scrape tool accepts these inputs: Firecrawl web scrape tool(url: 'string', page_options: 'object', extractor_options: 'object', timeout: 'integer') - Scrape webpages url using Firecrawl and return the contents url: 'Website URL', page_options: 'Options for page scraping', extractor_options: 'Options for data extraction', timeout: 'Timeout for the scraping operation'
```
I've added some default values and better description for timeout for fixing this issue.

[Bug] Improvements on default values and timeout description

---

crewai_tools/tools/nl2sql/nl2sql_tool.py

got this when trying it
```
...
File "/home/thiago/.cache/pypoetry/virtualenvs/data-analyst-5pqohAtO-py3.10/lib/python3.10/site-packages/pydantic/v1/schema.py", line 995, in encode_default
return pydantic_encoder(dft)
File "/home/thiago/.cache/pypoetry/virtualenvs/data-analyst-5pqohAtO-py3.10/lib/python3.10/site-packages/pydantic/v1/json.py", line 90, in pydantic_encoder
raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'FieldInfo' is not JSON serializable
```
possibly a version conflict due to getting BaseModel from v1
using a copy of the tool, with the fix, the issue has gone

Fix NL2SQL pydantic version conflict

---

crewai_tools/tools/code_docs_search_tool/code_docs_search_tool.py
crewai_tools/tools/csv_search_tool/csv_search_tool.py
crewai_tools/tools/directory_search_tool/directory_search_tool.py
crewai_tools/tools/docx_search_tool/docx_search_tool.py
crewai_tools/tools/github_search_tool/github_search_tool.py
crewai_tools/tools/json_search_tool/json_search_tool.py
crewai_tools/tools/mdx_seach_tool/mdx_search_tool.py
crewai_tools/tools/mysql_search_tool/mysql_search_tool.py
crewai_tools/tools/pdf_search_tool/pdf_search_tool.py
crewai_tools/tools/pg_seach_tool/pg_search_tool.py
crewai_tools/tools/txt_search_tool/txt_search_tool.py
crewai_tools/tools/website_search/website_search_tool.py
crewai_tools/tools/xml_search_tool/xml_search_tool.py
crewai_tools/tools/youtube_channel_search_tool/youtube_channel_search_tool.py
crewai_tools/tools/youtube_video_search_tool/youtube_video_search_tool.py

In the RAG tools, the `add()` method is setting `kwargs` variables. This introduces a scoping issue, making those variables unavailable to the rest of the class. The only change here is to lift that assignment into the constructor. This appears to be the cause of agents being unable to utilize the RAG tools to search or vectorize the source. 
I validated this allows the the `GithubSearchTool` and `DirectorySearchTool` RAG tools to work; I didn't have time to validate the others, but given the common cause I would expect the behavior is similar.
Related to this discussion, at least: https://github.com/crewAIInc/crewAI/discussions/1247
> Note: While this change enabled the RAG tools to vectorize and search the source, I noticed the agents are often dissatisfied with the output of the RAG …

Scoping issue causing error in RAG tools

---

crewai_tools/tools/file_writer_tool/file_writer_tool.py

- Fixed a KeyError caused by invalid access to kwargs dictionary key "directory" when no "directory" input was provided (kwargs["directory"]), it was replaced with the get() method to cover both use cases.
- The agent had trouble providing a correctly formatted input for the overwrite variable and would get stuck on the following error
Fixed it by changing the variable to string and converting it to boolean within the method, shows better behavior and resilience when used by agents.
- For content on the longer side, the agents tend to forget context when filling the rest of the arguments or closing the dictionary properly, changing the order of the arguments - placing 'content' last - significantly improved behavior.

Fixing errors of the File Writer tool

---

crewai_tools/tools/exa_tools/exa_base_tool.py
crewai_tools/tools/multion_tool/README.md

Updates the MultiOnTool README to correctly reference the MultiOn API key instead of Browserbase API key. This fixes inaccurate documentation that could confuse users trying to set up the tool.
- Changed "Browserbase API key" to "MultiOn API key" in the Arguments section
- Updated environment variable reference from `BROWSERBASE_API_KEY` to `MULTION_API_KEY`
- Fixed minor typo in the default value description
Documentation change only, no functional changes to test.
Fixes incorrect API key documentation in MultiOnTool README

 Fix API Key Reference in MultiOnTool README

---

crewai_tools/tools/exa_tools/exa_base_tool.py

This PR fixes a variable typo in the typo in exa_base_tool

fix: correct variable name typo in exa_base_tool

---

crewai_tools/tools/nl2sql/README.md

- Fixed typo: "passsed" → "passed"
- Fixed typo: "proivdes" → "provides"
- Fixed typo: "number of user" → "number of users"
- Removed unnecessary blank line in code section
- Maintained consistent spacing throughout the document
No testing required as these are documentation-only changes.
These changes improve the readability and professionalism of the NL2SQL Tool documentation without affecting any functionality.

docs: fix typos and formatting in NL2SQL tool README

---

crewai_tools/tools/firecrawl_scrape_website_tool/firecrawl_scrape_website_tool.py

Fix pydantic related errors on FirecrawlScrapeWebsiteTool

---

crewai_tools/tools/scrape_website_tool/scrape_website_tool.py

Fixes issue when web scraper concatenate words:
before: 
- her**eQ**uestio**nS**elected Optio**nP**oints Awarde**dQ**uestion - Use cas**eS**elected Option -Selected Optio**nP**oints -Points Awarde**dQ**uestion
after: 
- here Question Selected Option Points Awarded Question - Use case Selected Option - Selected Option Points - Points Awarded Question
Test code:
```python
from crewai_tools import ScrapeWebsiteTool
tool = ScrapeWebsiteTool(website_url='https://www.crewai.com/')
text = tool.run()
print(text)
```

fix: web scraper concatenate words

---

crewai_tools/tools/code_interpreter_tool/code_interpreter_tool.py
tests/tools/test_code_interpreter_tool.py

Fixes bug reported in issue https://github.com/crewAIInc/crewAI-tools/issues/158.
Problems identified:
1. Use of f-string causes text parsing problems, changed it to a list[str]
2. Type hinting was not properly applied, fixed that using proper imports.
Changes made:
1. Instead of using f-strings in `exec_run` here: `container.exec_run(f"pip install {library}")` and here: `cmd_to_run = f'python3 -c "{code}"'`, not using list: `container.exec_run(["pip", "install", library])` and `container.exec_run(["python3", "-c", code])`.
2. Proper imports from docker
3. Fixed `CodeInterpreterTool` unit testing
4. Added unit testing for multi-line code.
Now, when running the example from issue https://github.com/crewAIInc/crewAI-tools/issues/158:
```python
from crewai_tools import CodeInterpreterTool …
```

[BUG] `CodeInterpreterTool` cannot handle mutli-line code

---

crewai_tools/tools/llamaindex_tool/llamaindex_tool.py

- When passing result_as_answer=True, it will return ToolOutput so it won't pass pydantic validation as a string.
- Get content of ToolOutput before return.

fix: fix pydantic validation error

---

crewai_tools/__init__.py
crewai_tools/tools/__init__.py
crewai_tools/tools/serpapi_tool/README.md
crewai_tools/tools/serpapi_tool/serpapi_base_tool.py
crewai_tools/tools/serpapi_tool/serpapi_google_search_tool.py
crewai_tools/tools/serpapi_tool/serpapi_google_shopping_tool.py
pyproject.toml
uv.lock

Add supports for [SerpApi's](http://serpapi.com/) Google Search and Google Shopping
Google Search provides the capability to search information on the internet.
Google Shopping provides the capability to search shopping listing for given search query

feat: Add Google Search and Google Shopping tools

---

crewai_tools/tools/selenium_scraping_tool/README.md
crewai_tools/tools/selenium_scraping_tool/selenium_scraping_tool.py
tests/tools/selenium_scraping_tool_test.py

This pull request introduces a new feature to the `SeleniumScrapingTool` by adding a `return_html` flag. This is meant to provide users with the flexibility to choose between retrieving raw HTML content or plain text content from web pages during scraping operations.
- **Enhanced Flexibility**: Users can now choose the format of the scraped data, which is particularly useful for applications that require raw HTML for further processing or analysis.
- **Improved Usability**: The ability to toggle between HTML and text content makes the tool more versatile, catering to a broader range of use cases.
- **Backward Compatibility**: The default behaviour remains unchanged (returns text), ensuring that existing implementations are not affected unless the new flag is explicitly used.
- **Data …

Feat(SeleniumScrapingTool): Provide capability to return HTML

---

crewai_tools/tools/code_interpreter_tool/README.md
crewai_tools/tools/code_interpreter_tool/code_interpreter_tool.py

Goal is to avoid the error: CodeInterpreterTool Error while fetching server API version. 
See issue [#1555 ](https://github.com/crewAIInc/crewAI/issues/1555)crewai. 
solution code: 
```python 
from crewai_tools import CodeInterpreterTool
Agent(
...
tools=[CodeInterpreterTool(user_docker_base_url="<Docker Host Base Url>",
user_dockerfile_path="<Dockerfile_path>")],
)
```

Enabled connection to docker daemon with manual setting of docker base url for code interpreter tool. (Issue #1555) 

---

crewai_tools/tools/firecrawl_crawl_website_tool/firecrawl_crawl_website_tool.py

Fixes #144
Fixes issues that prevented a url from being used as the base url and provided API KEY from being used in the crawler. Add the ability to pass a previously built instance of `FirecrawlApp`
Tested on a crew in the following ways:
```python
from crewai_tools import FirecrawlCrawlWebsiteTool
crawler_tool = FirecrawlCrawlWebsiteTool()
```
```python
from crewai_tools import FirecrawlCrawlWebsiteTool
crawler_tool = FirecrawlCrawlWebsiteTool(
url="https://www.crewai.com/"
)
```
```python
from crewai_tools import FirecrawlCrawlWebsiteTool
crawler_tool = FirecrawlCrawlWebsiteTool(
api_key="value-for-the-key",
url="https://www.crewai.com/",
)
```
```python
from crewai_tools import FirecrawlCrawlWebsiteTool
from firecrawl import FirecrawlApp
app = FirecrawlApp(api_key = …
```

Fix url and api_key args on crawler tool

---

crewai_tools/tools/browserbase_load_tool/browserbase_load_tool.py

Addressing an issue in the `BrowserbaseLoadTool` where incorrect arguments were passed to the `Browserbase` class constructor. The old implementation caused a `TypeError` due to mismatched arguments. The updated code resolves this by correcting the initialization logic.
1. **Modified `BrowserbaseLoadTool` Initialization**:
- Updated `Browserbase` instantiation to correctly utilize `api_key` and other parameters.
- Removed redundant argument passing for `project_id` as it is not supported by the current `Browserbase` constructor.
2. **Environment Variable Integration**:
- Default values for `api_key` and `project_id` are now fetched directly from environment variables using `os.getenv`. This improves flexibility and reduces the need for redundant arguments in the constructor.
Running …

Update browserbase_load_tool.py | Fix for Browserbase Tool Initialization Issue

---

crewai_tools/tools/file_read_tool/file_read_tool.py

The FileReadTool currently has a _description_generator method which overwrites the BaseTool method of the same name. 
The BaseTool _description_generator creates a richly formatted description like so: 
```
Tool Name: Search the internet
Tool Arguments: {
'search_query': {
'description': 'Mandatory search query you want to use to search the internet',
'type': 'str'
}
}
Tool Description: A tool that can be used to search the internet with a search_query. Supports different search types: 'search' (default), 'news'
```
Whereas the current _description_generator on the FileReadTool creates something like this: 
```
A tool that reads file content. The default file is my_file.txt, but you can provide a different 'file_path' parameter to read another file.
```
The BaseTool's version of this …

Fix description on FileReadTool

---

crewai_tools/tools/serper_dev_tool/README.md
crewai_tools/tools/serper_dev_tool/serper_dev_tool.py
tests/tools/serper_dev_tool_test.py

Co-Authored-By: @Rolando-B
The previous enhancement PR #147 inadvertently removed crucial search localization parameters (`country`, `location`, `locale`) from the `SerperDevTool` class. These parameters are essential for users who need to perform geographically targeted searches.
- Restored the following parameters to `SerperDevTool`:
- `country` (maps to `gl` in Serper API)
- `location` (for city-specific searches)
- `locale` (maps to `hl` in Serper API)
- Updated payload construction in `_make_api_request` to include these parameters
- Updated usage examples to demonstrate localization parameters
These parameters are crucial for:
1. Getting region-specific search results (via `country`)
2. Targeting searches to specific cities (via `location`)
3. Getting results in specific languages …

fix(serper-dev): restore search localization parameters

---

crewai_tools/tools/databricks_query_tool/databricks_query_tool.py

rename schema to db_schema in DatabricksQueryTool to resolve:
```sh
crewAI % python src/crewai/runner.py
/Users/lorenzejay/workspace/crewAI/.venv/lib/python3.12/site-packages/pydantic/_internal/_fields.py:172: UserWarning: Field name "schema" in "DatabricksQueryToolSchema" shadows an attribute in parent "BaseModel"
warnings.warn(
/Users/lorenzejay/workspace/crewAI/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py:547: UserWarning: <built-in function callable> is not a Python type (it may be an instance of an object), Pydantic will allow any object with no validation since we cannot even enforce that the input is an instance of the given type. To get rid of this error wrap the type with `pydantic.SkipValidation`.
warn(
```

cleanup more warnings from tools

---

crewai_tools/tools/firecrawl_crawl_website_tool/README.md
crewai_tools/tools/firecrawl_crawl_website_tool/firecrawl_crawl_website_tool.py

FireCrawl API does not recognize sent parameters as this error describes:
``` terminal
HTTPError: Unexpected error during start crawl job: Status code 400. Bad Request -
[{'code': 'unrecognized_keys', 'keys': ['crawlerOptions', 'timeout'], 'path': [], 'message': 'Unrecognized key in body -- please review the v1 API documentation for request body changes'}]
```
Because FireCrawl API has been updated to v1. I updated the tool parameters to match v1 and updated their description in the ReadMe file

Fix: FirecrawlCrawlWebsiteTool update parameters for FireCrawl API v1 and update run arguments for agents

---

crewai_tools/tools/firecrawl_crawl_website_tool/README.md
crewai_tools/tools/firecrawl_crawl_website_tool/firecrawl_crawl_website_tool.py
crewai_tools/tools/firecrawl_scrape_website_tool/README.md
crewai_tools/tools/firecrawl_scrape_website_tool/firecrawl_scrape_website_tool.py
crewai_tools/tools/firecrawl_search_tool/README.md
crewai_tools/tools/firecrawl_search_tool/firecrawl_search_tool.py

Corrected error when calling all 3 Firecrawl tools : 
- Firecrawl Crawl
- Firecrawl Scrape
- Firecrawl Search
Passing optional variables in a dict a **kwargs for the firecrawl-py python package was not working.
Indeed, firecrawl uses : 
```
def func(url, var_1, ..., **kwargs):
params = {}
if var_1:
params['var_1'] = var_1
params.update(kwargs)
```
So calling :
```
options = {
'var_1': var_1,
...
}
firecrawl.func(url, options)
```
leads to a Too many positional arguments error

Fix firecrawl tool (Too many positional arguments)

---

crewai_tools/tools/vision_tool/vision_tool.py

Defaults to gpt-4o-mini otherwise

Allow setting custom LLM for the vision tool

---

crewai_tools/tools/firecrawl_scrape_website_tool/firecrawl_scrape_website_tool.py

Add missing config parameter and correct Dict type annotation
- Add required config parameter when creating the tool
- Change type hint from `dict` to `Dict` to resolve Pydantic validation issues

Fix FirecrawlScrapeWebsiteTool

---

crewai_tools/tools/qdrant_vector_search_tool/qdrant_search_tool.py

The built-in `callable` type is not subscriptable, and thus not usable in a type annotation. When this tool is used, this warning is generated:
```
.../_generate_schema.py:623: UserWarning: <built-in function callable> is not a Python type (it may be an instance of an object), Pydantic will allow any object with no validation since we cannot even enforce that the input is an instance of the given type. To get rid of this error wrap the type with `pydantic.SkipValidation`.
```
This change fixes the warning.

Fix `Callable` reference in QdrantVectorSearchTool

---

crewai_tools/tools/tavily_extractor_tool/README.md
crewai_tools/tools/tavily_extractor_tool/tavily_extractor_tool.py
crewai_tools/tools/tavily_search_tool/README.md
crewai_tools/tools/tavily_search_tool/tavily_search_tool.py
pyproject.toml

Introduce two new tools, `TavilyExtractorTool` and `TavilySearchTool`, enabling CrewAI agents to extract content and perform searches using the Tavily API. Include installation instructions and usage examples in the documentation. Update dependencies to include `tavily-python`.
Fixes #278

Add TavilyExtractorTool and TavilySearchTool with documentation

---

crewai_tools/__init__.py
crewai_tools/adapters/zapier_adapter.py
crewai_tools/tools/__init__.py
crewai_tools/tools/zapier_action_tool/README.md
crewai_tools/tools/zapier_action_tool/zapier_action_tool.py

- Introduced ZapierActionTool to execute Zapier actions with dynamic parameter handling.
- Added ZapierActionsAdapter to fetch available Zapier actions and convert them into BaseTool instances.
- Updated __init__.py files to include new tools and ensure proper imports.
- Created README.md for ZapierActionTools with installation instructions and usage examples.

feat: add ZapierActionTool and ZapierActionsAdapter for integrating with Zapier actions

---

crewai_tools/tools/file_read_tool/file_read_tool.py
tests/file_read_tool_test.py

Closes https://github.com/crewAIInc/crewAI/issues/2753
Quick fix to prevent FileReadTool break when the Agent call this with with `start_line: null` paramenter
``` 
"{\"file_path\": \"./file.md\", \"start_line\": null, \"line_count\": null}"
Error: Failed to read file ./file.md. unsupported operand type(s) for -: 'NoneType' and 'int'
```

fix: ensure the entire file will be read when the start_line is None

---

crewai_tools/adapters/mcp_adapter.py
crewai_tools/adapters/tool_collection.py
crewai_tools/tools/crewai_enterprise_tools/crewai_enterprise_tools.py
tests/adapters/mcp_adapter_test.py
tests/tools/tool_collection_test.py

We can now filter the available MCP tools 
```
with MCPServerAdapter(..., "tool1", "tool2") as filtered_tools:
```

Support to filter available MCP Tools

---

crewai_tools/tools/crewai_enterprise_tools/crewai_enterprise_tools.py
tests/tools/crewai_enterprise_tools_test.py

This commit introduces a new function, _parse_actions_list, to handle the parsing of a string representation of a list of tool names from environment variables. The CrewaiEnterpriseTools now utilizes this function to filter tools based on the parsed actions list, enhancing flexibility in tool selection. Additionally, a new test case is added to verify the correct usage of the environment actions list.

feat: add support for parsing actions list from environment variables

---

crewai_tools/adapters/enterprise_adapter.py

- Extracted schema property and required field extraction into separate methods for better readability and maintainability.
- Introduced methods to analyze field types and create Pydantic field definitions based on nullability and requirement status.
- Updated the _run method to handle required nullable fields, ensuring they are set to None if not provided in kwargs.

refactor: enhance schema handling in EnterpriseActionTool

---

crewai_tools/tools/scrapegraph_scrape_tool/scrapegraph_scrape_tool.py

This commit fixes a bug where `SCRAPEGRAPH_API_KEY` was never used to initialize `scrapegraph_py.Client`.

Use environment variable to initialize `scrapegraph_py.Client`

---

.github/workflows/generate-tool-specs.yml

This commit fixes a bug where Actions tried to commit directly in main, and that is not allowed for this repo. It fixes it by creating PRs.

Create PR for tool spec changes

---

crewai_tools/tools/exa_tools/exa_search_tool.py
tests/tools/test_import_without_warnings.py

This PR fixes a Pydantic deprecation warning by moving the `required=False` parameter from the deprecated `Field` extra arguments into the `json_schema_extra` parameter, ensuring compatibility with Pydantic V2.0+ and eliminating the deprecation warning that would cause issues in future versions.

fix: use json_schema_extra instead of deprecated Field extra args

---

crewai_tools/tools/rag/rag_tool.py

fix: remove debug logging from RAG tool

---

pyproject.toml
uv.lock

- Increment project version to 0.75.0
- Update crewai dependency to the latest version without a specific version constraint
- Update uv.lock to reflect changes in crewai version from 0.201.0 to 0.201.1

chore: update project version to 0.75.0 and revise crewai dependency
